default_args:
  num_steps: 20
  guidance: 3.5
  strength: 1.0
  tile_size: 512
  min_tile_size: 256
  overlap: 64
  fid_mode: patch
  fid_patch_size: 512
  fid_patches_per_image: 25

checkpoints:
  DIV2K:
    path: checkpoints/pgsr/stage1_df2k/20260506_042307_degpaired_presetrealesrgan_x4_str1_pw1_gate4_lpw0_lpp0p25_aug0_bmpsnr_crop2_dfm_dpw0p05_dlw0_dsg0p7_lora_r16_a16_d0_llr0p0001_tpominicontrol/best_model.pt
  RealSR:
    path: checkpoints/pgsr/stage2_realesrgan_mild/20260506_205402_degrealesrgan_presetrealesrgan_mild_x4_str1_pw1_gate4_lpw0_lpp0p25_aug0_bmpsnr_crop2_dfm_dpw0p05_dlw0_dsg0p7_detachv_lora_r16_a16_d0_llr0p0001_tpominicontrol/best_model.pt
  DRealSR:
    path: checkpoints/pgsr/stage2_realesrgan_mild/20260506_205402_degrealesrgan_presetrealesrgan_mild_x4_str1_pw1_gate4_lpw0_lpp0p25_aug0_bmpsnr_crop2_dfm_dpw0p05_dlw0_dsg0p7_detachv_lora_r16_a16_d0_llr0p0001_tpominicontrol/best_model.pt
