datasets:
  RealSR:
    selected_stems:
      - Canon_002
      - Canon_034
      - Nikon_009
      - Nikon_015
      - Nikon_025
      - Nikon_032
      - Nikon_041
      - Nikon_044
      - Nikon_046
